// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ValueStoreService.proto

package main

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StoreValueRequest struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StoreValueRequest) Reset()         { *m = StoreValueRequest{} }
func (m *StoreValueRequest) String() string { return proto.CompactTextString(m) }
func (*StoreValueRequest) ProtoMessage()    {}
func (*StoreValueRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbce9d90ab82b7ce, []int{0}
}

func (m *StoreValueRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StoreValueRequest.Unmarshal(m, b)
}
func (m *StoreValueRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StoreValueRequest.Marshal(b, m, deterministic)
}
func (m *StoreValueRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoreValueRequest.Merge(m, src)
}
func (m *StoreValueRequest) XXX_Size() int {
	return xxx_messageInfo_StoreValueRequest.Size(m)
}
func (m *StoreValueRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StoreValueRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StoreValueRequest proto.InternalMessageInfo

func (m *StoreValueRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *StoreValueRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type ValueResponse struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	CreatedAt            string   `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Version              int32    `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValueResponse) Reset()         { *m = ValueResponse{} }
func (m *ValueResponse) String() string { return proto.CompactTextString(m) }
func (*ValueResponse) ProtoMessage()    {}
func (*ValueResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbce9d90ab82b7ce, []int{1}
}

func (m *ValueResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValueResponse.Unmarshal(m, b)
}
func (m *ValueResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValueResponse.Marshal(b, m, deterministic)
}
func (m *ValueResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValueResponse.Merge(m, src)
}
func (m *ValueResponse) XXX_Size() int {
	return xxx_messageInfo_ValueResponse.Size(m)
}
func (m *ValueResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ValueResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ValueResponse proto.InternalMessageInfo

func (m *ValueResponse) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *ValueResponse) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *ValueResponse) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

type GetValueRequest struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Version              int32    `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetValueRequest) Reset()         { *m = GetValueRequest{} }
func (m *GetValueRequest) String() string { return proto.CompactTextString(m) }
func (*GetValueRequest) ProtoMessage()    {}
func (*GetValueRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbce9d90ab82b7ce, []int{2}
}

func (m *GetValueRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetValueRequest.Unmarshal(m, b)
}
func (m *GetValueRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetValueRequest.Marshal(b, m, deterministic)
}
func (m *GetValueRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetValueRequest.Merge(m, src)
}
func (m *GetValueRequest) XXX_Size() int {
	return xxx_messageInfo_GetValueRequest.Size(m)
}
func (m *GetValueRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetValueRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetValueRequest proto.InternalMessageInfo

func (m *GetValueRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *GetValueRequest) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func init() {
	proto.RegisterType((*StoreValueRequest)(nil), "main.StoreValueRequest")
	proto.RegisterType((*ValueResponse)(nil), "main.ValueResponse")
	proto.RegisterType((*GetValueRequest)(nil), "main.GetValueRequest")
}

func init() { proto.RegisterFile("ValueStoreService.proto", fileDescriptor_fbce9d90ab82b7ce) }

var fileDescriptor_fbce9d90ab82b7ce = []byte{
	// 259 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x0f, 0x4b, 0xcc, 0x29,
	0x4d, 0x0d, 0x2e, 0xc9, 0x2f, 0x4a, 0x0d, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28,
	0xca, 0x2f, 0xc9, 0x17, 0x62, 0xc9, 0x4d, 0xcc, 0xcc, 0x53, 0xb2, 0xe5, 0x12, 0x04, 0xcb, 0x81,
	0x55, 0x05, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x08, 0x09, 0x71, 0xb1, 0x14, 0x24, 0x96, 0x64,
	0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x81, 0xd9, 0x42, 0x22, 0x5c, 0xac, 0x65, 0x20, 0x35,
	0x12, 0x4c, 0x60, 0x41, 0x08, 0x47, 0x29, 0x86, 0x8b, 0x17, 0xaa, 0xb3, 0xb8, 0x20, 0x3f, 0xaf,
	0x38, 0x15, 0xab, 0x56, 0x59, 0x2e, 0xae, 0xe4, 0xa2, 0xd4, 0xc4, 0x92, 0xd4, 0x94, 0xf8, 0xc4,
	0x12, 0xa8, 0x7e, 0x4e, 0xa8, 0x88, 0x63, 0x89, 0x90, 0x04, 0x17, 0x7b, 0x59, 0x6a, 0x51, 0x71,
	0x66, 0x7e, 0x9e, 0x04, 0xb3, 0x02, 0xa3, 0x06, 0x6b, 0x10, 0x8c, 0xab, 0x64, 0xcf, 0xc5, 0xef,
	0x9e, 0x5a, 0x42, 0xd0, 0x69, 0x48, 0x06, 0x30, 0xa1, 0x18, 0x60, 0xd4, 0xc2, 0xc8, 0xc5, 0x85,
	0xf0, 0xbf, 0x90, 0x0d, 0x17, 0x17, 0xc2, 0xb3, 0x42, 0xe2, 0x7a, 0xa0, 0x10, 0xd0, 0xc3, 0xf0,
	0xbe, 0x94, 0x30, 0x44, 0x02, 0xc5, 0x63, 0x4a, 0x0c, 0x42, 0x16, 0x5c, 0x1c, 0x30, 0xd7, 0x08,
	0x89, 0x42, 0x94, 0xa0, 0xb9, 0x0e, 0x87, 0x4e, 0x27, 0x7d, 0x2e, 0x91, 0xe4, 0xfc, 0x5c, 0xbd,
	0xd4, 0x8a, 0xc4, 0xdc, 0x82, 0x9c, 0x54, 0xbd, 0xf4, 0xa2, 0x82, 0xe4, 0x94, 0xd4, 0xdc, 0x7c,
	0x27, 0x7e, 0x84, 0xdb, 0x02, 0x40, 0x71, 0x12, 0xc0, 0xb8, 0x88, 0x89, 0xd9, 0xc3, 0x27, 0x3c,
	0x89, 0x0d, 0x1c, 0x45, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xbd, 0xdd, 0xfb, 0xac, 0xbd,
	0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ValueStoreClient is the client API for ValueStore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ValueStoreClient interface {
	StoreValue(ctx context.Context, in *StoreValueRequest, opts ...grpc.CallOption) (*ValueResponse, error)
	GetValue(ctx context.Context, in *GetValueRequest, opts ...grpc.CallOption) (*ValueResponse, error)
}

type valueStoreClient struct {
	cc *grpc.ClientConn
}

func NewValueStoreClient(cc *grpc.ClientConn) ValueStoreClient {
	return &valueStoreClient{cc}
}

func (c *valueStoreClient) StoreValue(ctx context.Context, in *StoreValueRequest, opts ...grpc.CallOption) (*ValueResponse, error) {
	out := new(ValueResponse)
	err := c.cc.Invoke(ctx, "/main.ValueStore/StoreValue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *valueStoreClient) GetValue(ctx context.Context, in *GetValueRequest, opts ...grpc.CallOption) (*ValueResponse, error) {
	out := new(ValueResponse)
	err := c.cc.Invoke(ctx, "/main.ValueStore/GetValue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ValueStoreServer is the server API for ValueStore service.
type ValueStoreServer interface {
	StoreValue(context.Context, *StoreValueRequest) (*ValueResponse, error)
	GetValue(context.Context, *GetValueRequest) (*ValueResponse, error)
}

func RegisterValueStoreServer(s *grpc.Server, srv ValueStoreServer) {
	s.RegisterService(&_ValueStore_serviceDesc, srv)
}

func _ValueStore_StoreValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ValueStoreServer).StoreValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.ValueStore/StoreValue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ValueStoreServer).StoreValue(ctx, req.(*StoreValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ValueStore_GetValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ValueStoreServer).GetValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.ValueStore/GetValue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ValueStoreServer).GetValue(ctx, req.(*GetValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ValueStore_serviceDesc = grpc.ServiceDesc{
	ServiceName: "main.ValueStore",
	HandlerType: (*ValueStoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StoreValue",
			Handler:    _ValueStore_StoreValue_Handler,
		},
		{
			MethodName: "GetValue",
			Handler:    _ValueStore_GetValue_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ValueStoreService.proto",
}
