// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ValueStoreService.proto

package main

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StoreValueRequest struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StoreValueRequest) Reset()         { *m = StoreValueRequest{} }
func (m *StoreValueRequest) String() string { return proto.CompactTextString(m) }
func (*StoreValueRequest) ProtoMessage()    {}
func (*StoreValueRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbce9d90ab82b7ce, []int{0}
}

func (m *StoreValueRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StoreValueRequest.Unmarshal(m, b)
}
func (m *StoreValueRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StoreValueRequest.Marshal(b, m, deterministic)
}
func (m *StoreValueRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoreValueRequest.Merge(m, src)
}
func (m *StoreValueRequest) XXX_Size() int {
	return xxx_messageInfo_StoreValueRequest.Size(m)
}
func (m *StoreValueRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StoreValueRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StoreValueRequest proto.InternalMessageInfo

func (m *StoreValueRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *StoreValueRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type StoreValueResponse struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Path                 string   `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	CreatedAt            string   `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Version              int64    `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StoreValueResponse) Reset()         { *m = StoreValueResponse{} }
func (m *StoreValueResponse) String() string { return proto.CompactTextString(m) }
func (*StoreValueResponse) ProtoMessage()    {}
func (*StoreValueResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbce9d90ab82b7ce, []int{1}
}

func (m *StoreValueResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StoreValueResponse.Unmarshal(m, b)
}
func (m *StoreValueResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StoreValueResponse.Marshal(b, m, deterministic)
}
func (m *StoreValueResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoreValueResponse.Merge(m, src)
}
func (m *StoreValueResponse) XXX_Size() int {
	return xxx_messageInfo_StoreValueResponse.Size(m)
}
func (m *StoreValueResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StoreValueResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StoreValueResponse proto.InternalMessageInfo

func (m *StoreValueResponse) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *StoreValueResponse) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *StoreValueResponse) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *StoreValueResponse) GetVersion() int64 {
	if m != nil {
		return m.Version
	}
	return 0
}

type GetValueByPathRequest struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Version              int64    `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetValueByPathRequest) Reset()         { *m = GetValueByPathRequest{} }
func (m *GetValueByPathRequest) String() string { return proto.CompactTextString(m) }
func (*GetValueByPathRequest) ProtoMessage()    {}
func (*GetValueByPathRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbce9d90ab82b7ce, []int{2}
}

func (m *GetValueByPathRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetValueByPathRequest.Unmarshal(m, b)
}
func (m *GetValueByPathRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetValueByPathRequest.Marshal(b, m, deterministic)
}
func (m *GetValueByPathRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetValueByPathRequest.Merge(m, src)
}
func (m *GetValueByPathRequest) XXX_Size() int {
	return xxx_messageInfo_GetValueByPathRequest.Size(m)
}
func (m *GetValueByPathRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetValueByPathRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetValueByPathRequest proto.InternalMessageInfo

func (m *GetValueByPathRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *GetValueByPathRequest) GetVersion() int64 {
	if m != nil {
		return m.Version
	}
	return 0
}

type GetValueByUUIDRequest struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetValueByUUIDRequest) Reset()         { *m = GetValueByUUIDRequest{} }
func (m *GetValueByUUIDRequest) String() string { return proto.CompactTextString(m) }
func (*GetValueByUUIDRequest) ProtoMessage()    {}
func (*GetValueByUUIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbce9d90ab82b7ce, []int{3}
}

func (m *GetValueByUUIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetValueByUUIDRequest.Unmarshal(m, b)
}
func (m *GetValueByUUIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetValueByUUIDRequest.Marshal(b, m, deterministic)
}
func (m *GetValueByUUIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetValueByUUIDRequest.Merge(m, src)
}
func (m *GetValueByUUIDRequest) XXX_Size() int {
	return xxx_messageInfo_GetValueByUUIDRequest.Size(m)
}
func (m *GetValueByUUIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetValueByUUIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetValueByUUIDRequest proto.InternalMessageInfo

func (m *GetValueByUUIDRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

type GetValueResponse struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetValueResponse) Reset()         { *m = GetValueResponse{} }
func (m *GetValueResponse) String() string { return proto.CompactTextString(m) }
func (*GetValueResponse) ProtoMessage()    {}
func (*GetValueResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbce9d90ab82b7ce, []int{4}
}

func (m *GetValueResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetValueResponse.Unmarshal(m, b)
}
func (m *GetValueResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetValueResponse.Marshal(b, m, deterministic)
}
func (m *GetValueResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetValueResponse.Merge(m, src)
}
func (m *GetValueResponse) XXX_Size() int {
	return xxx_messageInfo_GetValueResponse.Size(m)
}
func (m *GetValueResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetValueResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetValueResponse proto.InternalMessageInfo

func (m *GetValueResponse) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *GetValueResponse) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*StoreValueRequest)(nil), "main.StoreValueRequest")
	proto.RegisterType((*StoreValueResponse)(nil), "main.StoreValueResponse")
	proto.RegisterType((*GetValueByPathRequest)(nil), "main.GetValueByPathRequest")
	proto.RegisterType((*GetValueByUUIDRequest)(nil), "main.GetValueByUUIDRequest")
	proto.RegisterType((*GetValueResponse)(nil), "main.GetValueResponse")
}

func init() { proto.RegisterFile("ValueStoreService.proto", fileDescriptor_fbce9d90ab82b7ce) }

var fileDescriptor_fbce9d90ab82b7ce = []byte{
	// 317 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0x5f, 0x4b, 0xf3, 0x30,
	0x14, 0xc6, 0xdf, 0x76, 0x7b, 0x95, 0x9d, 0x0b, 0xff, 0x84, 0xe9, 0xc2, 0x44, 0x18, 0xbd, 0x1a,
	0x08, 0x15, 0xf4, 0x56, 0x2f, 0x36, 0x94, 0x29, 0x78, 0x51, 0x3a, 0xa6, 0x97, 0x12, 0xdb, 0x83,
	0x2b, 0xac, 0x4d, 0x4d, 0xd3, 0xa2, 0x5f, 0xc7, 0x6f, 0xe6, 0x37, 0x91, 0xa4, 0xd6, 0xa6, 0x76,
	0xdb, 0x5d, 0x92, 0xe7, 0x39, 0xbf, 0xe4, 0x3c, 0x27, 0x30, 0x78, 0x64, 0xab, 0x1c, 0xe7, 0x92,
	0x0b, 0x9c, 0xa3, 0x28, 0xa2, 0x00, 0xdd, 0x54, 0x70, 0xc9, 0x49, 0x37, 0x66, 0x51, 0xe2, 0x5c,
	0xc3, 0xa1, 0xd6, 0xb4, 0xcb, 0xc7, 0xb7, 0x1c, 0x33, 0x49, 0x08, 0x74, 0x53, 0x26, 0x97, 0xd4,
	0x1a, 0x59, 0xe3, 0x9e, 0xaf, 0xd7, 0xa4, 0x0f, 0xff, 0x0b, 0xe5, 0xa1, 0xb6, 0x3e, 0x2c, 0x37,
	0x4e, 0x0e, 0xc4, 0x2c, 0xcf, 0x52, 0x9e, 0x64, 0xa8, 0xea, 0xf3, 0x3c, 0x0a, 0xab, 0x7a, 0xb5,
	0xfe, 0x65, 0xda, 0x06, 0xf3, 0x14, 0x20, 0x10, 0xc8, 0x24, 0x86, 0xcf, 0x4c, 0xd2, 0x8e, 0x56,
	0x7a, 0x3f, 0x27, 0x13, 0x49, 0x28, 0xec, 0x16, 0x28, 0xb2, 0x88, 0x27, 0xb4, 0x3b, 0xb2, 0xc6,
	0x1d, 0xbf, 0xda, 0x3a, 0xb7, 0x70, 0x34, 0x43, 0xa9, 0x2f, 0x9d, 0x7e, 0x78, 0x4c, 0x2e, 0xb7,
	0xbd, 0xdc, 0xc0, 0xd8, 0x4d, 0xcc, 0x99, 0x89, 0x59, 0x2c, 0xee, 0x6f, 0x0c, 0xcc, 0xdf, 0x06,
	0x9c, 0x2b, 0x38, 0xa8, 0xcc, 0x5b, 0x1b, 0x5d, 0x1b, 0xd4, 0xc5, 0x97, 0x05, 0x50, 0x4f, 0x82,
	0x4c, 0x00, 0xea, 0xdc, 0xc8, 0xc0, 0x55, 0xb3, 0x70, 0x5b, 0x83, 0x18, 0xd2, 0xb6, 0x50, 0xde,
	0xec, 0xfc, 0x23, 0x33, 0xd8, 0x6b, 0x66, 0x40, 0x4e, 0x4a, 0xf7, 0xda, 0x64, 0x86, 0xc7, 0x4d,
	0x71, 0x13, 0x48, 0xa5, 0xd0, 0x06, 0x19, 0xd9, 0x6c, 0x06, 0x4d, 0xcf, 0xa1, 0x1f, 0xf0, 0xd8,
	0xc5, 0x77, 0x16, 0xa7, 0x2b, 0x74, 0x5f, 0x45, 0x1a, 0x84, 0x18, 0xf3, 0xe9, 0x7e, 0xdd, 0xb8,
	0xa7, 0xbe, 0x9e, 0x67, 0x7d, 0xda, 0x9d, 0xbb, 0x87, 0xa7, 0x97, 0x1d, 0xfd, 0x13, 0x2f, 0xbf,
	0x03, 0x00, 0x00, 0xff, 0xff, 0x18, 0x1f, 0x1e, 0xd8, 0xa4, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ValueStoreClient is the client API for ValueStore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ValueStoreClient interface {
	StoreValue(ctx context.Context, in *StoreValueRequest, opts ...grpc.CallOption) (*StoreValueResponse, error)
	GetValueByPath(ctx context.Context, in *GetValueByPathRequest, opts ...grpc.CallOption) (*GetValueResponse, error)
	GetValueByUUID(ctx context.Context, in *GetValueByUUIDRequest, opts ...grpc.CallOption) (*GetValueResponse, error)
}

type valueStoreClient struct {
	cc *grpc.ClientConn
}

func NewValueStoreClient(cc *grpc.ClientConn) ValueStoreClient {
	return &valueStoreClient{cc}
}

func (c *valueStoreClient) StoreValue(ctx context.Context, in *StoreValueRequest, opts ...grpc.CallOption) (*StoreValueResponse, error) {
	out := new(StoreValueResponse)
	err := c.cc.Invoke(ctx, "/main.ValueStore/StoreValue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *valueStoreClient) GetValueByPath(ctx context.Context, in *GetValueByPathRequest, opts ...grpc.CallOption) (*GetValueResponse, error) {
	out := new(GetValueResponse)
	err := c.cc.Invoke(ctx, "/main.ValueStore/GetValueByPath", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *valueStoreClient) GetValueByUUID(ctx context.Context, in *GetValueByUUIDRequest, opts ...grpc.CallOption) (*GetValueResponse, error) {
	out := new(GetValueResponse)
	err := c.cc.Invoke(ctx, "/main.ValueStore/GetValueByUUID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ValueStoreServer is the server API for ValueStore service.
type ValueStoreServer interface {
	StoreValue(context.Context, *StoreValueRequest) (*StoreValueResponse, error)
	GetValueByPath(context.Context, *GetValueByPathRequest) (*GetValueResponse, error)
	GetValueByUUID(context.Context, *GetValueByUUIDRequest) (*GetValueResponse, error)
}

func RegisterValueStoreServer(s *grpc.Server, srv ValueStoreServer) {
	s.RegisterService(&_ValueStore_serviceDesc, srv)
}

func _ValueStore_StoreValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ValueStoreServer).StoreValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.ValueStore/StoreValue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ValueStoreServer).StoreValue(ctx, req.(*StoreValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ValueStore_GetValueByPath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetValueByPathRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ValueStoreServer).GetValueByPath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.ValueStore/GetValueByPath",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ValueStoreServer).GetValueByPath(ctx, req.(*GetValueByPathRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ValueStore_GetValueByUUID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetValueByUUIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ValueStoreServer).GetValueByUUID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.ValueStore/GetValueByUUID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ValueStoreServer).GetValueByUUID(ctx, req.(*GetValueByUUIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ValueStore_serviceDesc = grpc.ServiceDesc{
	ServiceName: "main.ValueStore",
	HandlerType: (*ValueStoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StoreValue",
			Handler:    _ValueStore_StoreValue_Handler,
		},
		{
			MethodName: "GetValueByPath",
			Handler:    _ValueStore_GetValueByPath_Handler,
		},
		{
			MethodName: "GetValueByUUID",
			Handler:    _ValueStore_GetValueByUUID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ValueStoreService.proto",
}
