// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ValueStoreService.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SetValueRequest struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetValueRequest) Reset()         { *m = SetValueRequest{} }
func (m *SetValueRequest) String() string { return proto.CompactTextString(m) }
func (*SetValueRequest) ProtoMessage()    {}
func (*SetValueRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbce9d90ab82b7ce, []int{0}
}

func (m *SetValueRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetValueRequest.Unmarshal(m, b)
}
func (m *SetValueRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetValueRequest.Marshal(b, m, deterministic)
}
func (m *SetValueRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetValueRequest.Merge(m, src)
}
func (m *SetValueRequest) XXX_Size() int {
	return xxx_messageInfo_SetValueRequest.Size(m)
}
func (m *SetValueRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetValueRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetValueRequest proto.InternalMessageInfo

func (m *SetValueRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *SetValueRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type SetValueResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Path                 string   `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	CreatedAt            string   `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Version              int64    `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetValueResponse) Reset()         { *m = SetValueResponse{} }
func (m *SetValueResponse) String() string { return proto.CompactTextString(m) }
func (*SetValueResponse) ProtoMessage()    {}
func (*SetValueResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbce9d90ab82b7ce, []int{1}
}

func (m *SetValueResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetValueResponse.Unmarshal(m, b)
}
func (m *SetValueResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetValueResponse.Marshal(b, m, deterministic)
}
func (m *SetValueResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetValueResponse.Merge(m, src)
}
func (m *SetValueResponse) XXX_Size() int {
	return xxx_messageInfo_SetValueResponse.Size(m)
}
func (m *SetValueResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetValueResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetValueResponse proto.InternalMessageInfo

func (m *SetValueResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SetValueResponse) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *SetValueResponse) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *SetValueResponse) GetVersion() int64 {
	if m != nil {
		return m.Version
	}
	return 0
}

type GetValueByPathRequest struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetValueByPathRequest) Reset()         { *m = GetValueByPathRequest{} }
func (m *GetValueByPathRequest) String() string { return proto.CompactTextString(m) }
func (*GetValueByPathRequest) ProtoMessage()    {}
func (*GetValueByPathRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbce9d90ab82b7ce, []int{2}
}

func (m *GetValueByPathRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetValueByPathRequest.Unmarshal(m, b)
}
func (m *GetValueByPathRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetValueByPathRequest.Marshal(b, m, deterministic)
}
func (m *GetValueByPathRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetValueByPathRequest.Merge(m, src)
}
func (m *GetValueByPathRequest) XXX_Size() int {
	return xxx_messageInfo_GetValueByPathRequest.Size(m)
}
func (m *GetValueByPathRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetValueByPathRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetValueByPathRequest proto.InternalMessageInfo

func (m *GetValueByPathRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type GetValueByIdRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetValueByIdRequest) Reset()         { *m = GetValueByIdRequest{} }
func (m *GetValueByIdRequest) String() string { return proto.CompactTextString(m) }
func (*GetValueByIdRequest) ProtoMessage()    {}
func (*GetValueByIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbce9d90ab82b7ce, []int{3}
}

func (m *GetValueByIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetValueByIdRequest.Unmarshal(m, b)
}
func (m *GetValueByIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetValueByIdRequest.Marshal(b, m, deterministic)
}
func (m *GetValueByIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetValueByIdRequest.Merge(m, src)
}
func (m *GetValueByIdRequest) XXX_Size() int {
	return xxx_messageInfo_GetValueByIdRequest.Size(m)
}
func (m *GetValueByIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetValueByIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetValueByIdRequest proto.InternalMessageInfo

func (m *GetValueByIdRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetValueResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetValueResponse) Reset()         { *m = GetValueResponse{} }
func (m *GetValueResponse) String() string { return proto.CompactTextString(m) }
func (*GetValueResponse) ProtoMessage()    {}
func (*GetValueResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbce9d90ab82b7ce, []int{4}
}

func (m *GetValueResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetValueResponse.Unmarshal(m, b)
}
func (m *GetValueResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetValueResponse.Marshal(b, m, deterministic)
}
func (m *GetValueResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetValueResponse.Merge(m, src)
}
func (m *GetValueResponse) XXX_Size() int {
	return xxx_messageInfo_GetValueResponse.Size(m)
}
func (m *GetValueResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetValueResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetValueResponse proto.InternalMessageInfo

func (m *GetValueResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetValueResponse) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type DeleteValueByPathRequest struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteValueByPathRequest) Reset()         { *m = DeleteValueByPathRequest{} }
func (m *DeleteValueByPathRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteValueByPathRequest) ProtoMessage()    {}
func (*DeleteValueByPathRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbce9d90ab82b7ce, []int{5}
}

func (m *DeleteValueByPathRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteValueByPathRequest.Unmarshal(m, b)
}
func (m *DeleteValueByPathRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteValueByPathRequest.Marshal(b, m, deterministic)
}
func (m *DeleteValueByPathRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteValueByPathRequest.Merge(m, src)
}
func (m *DeleteValueByPathRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteValueByPathRequest.Size(m)
}
func (m *DeleteValueByPathRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteValueByPathRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteValueByPathRequest proto.InternalMessageInfo

func (m *DeleteValueByPathRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type DeleteValueByIdRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteValueByIdRequest) Reset()         { *m = DeleteValueByIdRequest{} }
func (m *DeleteValueByIdRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteValueByIdRequest) ProtoMessage()    {}
func (*DeleteValueByIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbce9d90ab82b7ce, []int{6}
}

func (m *DeleteValueByIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteValueByIdRequest.Unmarshal(m, b)
}
func (m *DeleteValueByIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteValueByIdRequest.Marshal(b, m, deterministic)
}
func (m *DeleteValueByIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteValueByIdRequest.Merge(m, src)
}
func (m *DeleteValueByIdRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteValueByIdRequest.Size(m)
}
func (m *DeleteValueByIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteValueByIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteValueByIdRequest proto.InternalMessageInfo

func (m *DeleteValueByIdRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteValueResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Path                 string   `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteValueResponse) Reset()         { *m = DeleteValueResponse{} }
func (m *DeleteValueResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteValueResponse) ProtoMessage()    {}
func (*DeleteValueResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbce9d90ab82b7ce, []int{7}
}

func (m *DeleteValueResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteValueResponse.Unmarshal(m, b)
}
func (m *DeleteValueResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteValueResponse.Marshal(b, m, deterministic)
}
func (m *DeleteValueResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteValueResponse.Merge(m, src)
}
func (m *DeleteValueResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteValueResponse.Size(m)
}
func (m *DeleteValueResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteValueResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteValueResponse proto.InternalMessageInfo

func (m *DeleteValueResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DeleteValueResponse) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func init() {
	proto.RegisterType((*SetValueRequest)(nil), "proto.SetValueRequest")
	proto.RegisterType((*SetValueResponse)(nil), "proto.SetValueResponse")
	proto.RegisterType((*GetValueByPathRequest)(nil), "proto.GetValueByPathRequest")
	proto.RegisterType((*GetValueByIdRequest)(nil), "proto.GetValueByIdRequest")
	proto.RegisterType((*GetValueResponse)(nil), "proto.GetValueResponse")
	proto.RegisterType((*DeleteValueByPathRequest)(nil), "proto.DeleteValueByPathRequest")
	proto.RegisterType((*DeleteValueByIdRequest)(nil), "proto.DeleteValueByIdRequest")
	proto.RegisterType((*DeleteValueResponse)(nil), "proto.DeleteValueResponse")
}

func init() { proto.RegisterFile("ValueStoreService.proto", fileDescriptor_fbce9d90ab82b7ce) }

var fileDescriptor_fbce9d90ab82b7ce = []byte{
	// 362 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0xd1, 0x4b, 0xc2, 0x50,
	0x14, 0xc6, 0xdb, 0xa6, 0x95, 0x87, 0x50, 0x3b, 0x9a, 0x8e, 0x91, 0x24, 0x83, 0x40, 0x08, 0x16,
	0xd4, 0x4b, 0x11, 0x3d, 0x24, 0x85, 0x09, 0x11, 0x32, 0xa1, 0x1e, 0x63, 0x6d, 0x87, 0x1c, 0xa8,
	0x77, 0xdd, 0x5d, 0xa5, 0x1e, 0xfb, 0x57, 0xfa, 0x4b, 0xc3, 0xeb, 0x74, 0xd3, 0xa9, 0xd5, 0xd3,
	0x76, 0xcf, 0xfd, 0xce, 0xef, 0x7e, 0xe7, 0x7c, 0x50, 0x7d, 0x72, 0xfa, 0x23, 0xea, 0x0a, 0xc6,
	0xa9, 0x4b, 0x7c, 0xec, 0xbb, 0x64, 0x05, 0x9c, 0x09, 0x86, 0x59, 0xf9, 0x31, 0xaf, 0xa0, 0xd0,
	0x25, 0x21, 0x45, 0x36, 0xbd, 0x8f, 0x28, 0x14, 0x88, 0x90, 0x09, 0x1c, 0xd1, 0xd3, 0x95, 0xba,
	0xd2, 0xc8, 0xd9, 0xf2, 0x1f, 0xcb, 0x90, 0x1d, 0x4f, 0x34, 0xba, 0x2a, 0x8b, 0xd3, 0x83, 0xc9,
	0xa0, 0x18, 0x37, 0x87, 0x01, 0x1b, 0x86, 0x84, 0x79, 0x50, 0x7d, 0x2f, 0xea, 0x55, 0x7d, 0x6f,
	0x4e, 0x53, 0x13, 0xb4, 0x1a, 0x80, 0xcb, 0xc9, 0x11, 0xe4, 0xbd, 0x38, 0x42, 0xd7, 0xe4, 0x4d,
	0x2e, 0xaa, 0xdc, 0x08, 0xd4, 0x61, 0x67, 0x4c, 0x3c, 0xf4, 0xd9, 0x50, 0xcf, 0xd4, 0x95, 0x86,
	0x66, 0xcf, 0x8e, 0xe6, 0x09, 0x1c, 0xb4, 0xa2, 0x07, 0x9b, 0x9f, 0x1d, 0x47, 0xf4, 0x36, 0x78,
	0x36, 0x8f, 0xa1, 0x14, 0x8b, 0xdb, 0xde, 0x4c, 0xba, 0x64, 0xd0, 0xbc, 0x80, 0x62, 0xeb, 0xb7,
	0x21, 0x56, 0x8f, 0x6f, 0x81, 0x7e, 0x4b, 0x7d, 0x12, 0xf4, 0x47, 0x43, 0x0d, 0xa8, 0x2c, 0xe8,
	0xd7, 0x7b, 0xba, 0x84, 0x52, 0x42, 0xf9, 0x9f, 0xdd, 0x9e, 0x7d, 0x69, 0x00, 0x71, 0xe6, 0x78,
	0x0d, 0xbb, 0xb3, 0x88, 0xb0, 0x32, 0x8d, 0xde, 0x5a, 0x0a, 0xdc, 0xa8, 0xa6, 0xea, 0xd3, 0xf7,
	0xcc, 0x2d, 0x6c, 0x43, 0x7e, 0x71, 0xe1, 0x78, 0x18, 0x89, 0x57, 0xe6, 0x30, 0x47, 0xb5, 0xd2,
	0xa8, 0x3b, 0xd8, 0x4b, 0xc6, 0x81, 0x46, 0x0a, 0x34, 0xdf, 0xc7, 0x26, 0x8c, 0x0d, 0xfb, 0xa9,
	0xa5, 0xe3, 0x51, 0xa4, 0x5f, 0x17, 0x87, 0x61, 0xa4, 0x05, 0x09, 0xe6, 0x23, 0x14, 0x96, 0x82,
	0xc1, 0xda, 0x2a, 0x62, 0x6c, 0x70, 0x23, 0xaf, 0x79, 0x0a, 0x65, 0x97, 0x0d, 0x2c, 0xfa, 0x70,
	0x06, 0x41, 0x9f, 0xac, 0x37, 0x1e, 0xb8, 0x1e, 0x0d, 0x58, 0xb3, 0x10, 0x07, 0xd3, 0x99, 0xb4,
	0x77, 0x94, 0x6f, 0x55, 0xbb, 0x7f, 0x78, 0x7e, 0xdd, 0x96, 0xb4, 0xf3, 0x9f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xcc, 0x38, 0x01, 0xc5, 0xae, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ValueStoreClient is the client API for ValueStore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ValueStoreClient interface {
	SetValue(ctx context.Context, in *SetValueRequest, opts ...grpc.CallOption) (*SetValueResponse, error)
	GetValueByPath(ctx context.Context, in *GetValueByPathRequest, opts ...grpc.CallOption) (*GetValueResponse, error)
	GetValueById(ctx context.Context, in *GetValueByIdRequest, opts ...grpc.CallOption) (*GetValueResponse, error)
	DeleteValueByPath(ctx context.Context, in *DeleteValueByPathRequest, opts ...grpc.CallOption) (*DeleteValueResponse, error)
	DeleteValueById(ctx context.Context, in *DeleteValueByIdRequest, opts ...grpc.CallOption) (*DeleteValueResponse, error)
}

type valueStoreClient struct {
	cc *grpc.ClientConn
}

func NewValueStoreClient(cc *grpc.ClientConn) ValueStoreClient {
	return &valueStoreClient{cc}
}

func (c *valueStoreClient) SetValue(ctx context.Context, in *SetValueRequest, opts ...grpc.CallOption) (*SetValueResponse, error) {
	out := new(SetValueResponse)
	err := c.cc.Invoke(ctx, "/proto.ValueStore/SetValue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *valueStoreClient) GetValueByPath(ctx context.Context, in *GetValueByPathRequest, opts ...grpc.CallOption) (*GetValueResponse, error) {
	out := new(GetValueResponse)
	err := c.cc.Invoke(ctx, "/proto.ValueStore/GetValueByPath", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *valueStoreClient) GetValueById(ctx context.Context, in *GetValueByIdRequest, opts ...grpc.CallOption) (*GetValueResponse, error) {
	out := new(GetValueResponse)
	err := c.cc.Invoke(ctx, "/proto.ValueStore/GetValueById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *valueStoreClient) DeleteValueByPath(ctx context.Context, in *DeleteValueByPathRequest, opts ...grpc.CallOption) (*DeleteValueResponse, error) {
	out := new(DeleteValueResponse)
	err := c.cc.Invoke(ctx, "/proto.ValueStore/DeleteValueByPath", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *valueStoreClient) DeleteValueById(ctx context.Context, in *DeleteValueByIdRequest, opts ...grpc.CallOption) (*DeleteValueResponse, error) {
	out := new(DeleteValueResponse)
	err := c.cc.Invoke(ctx, "/proto.ValueStore/DeleteValueById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ValueStoreServer is the server API for ValueStore service.
type ValueStoreServer interface {
	SetValue(context.Context, *SetValueRequest) (*SetValueResponse, error)
	GetValueByPath(context.Context, *GetValueByPathRequest) (*GetValueResponse, error)
	GetValueById(context.Context, *GetValueByIdRequest) (*GetValueResponse, error)
	DeleteValueByPath(context.Context, *DeleteValueByPathRequest) (*DeleteValueResponse, error)
	DeleteValueById(context.Context, *DeleteValueByIdRequest) (*DeleteValueResponse, error)
}

func RegisterValueStoreServer(s *grpc.Server, srv ValueStoreServer) {
	s.RegisterService(&_ValueStore_serviceDesc, srv)
}

func _ValueStore_SetValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ValueStoreServer).SetValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ValueStore/SetValue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ValueStoreServer).SetValue(ctx, req.(*SetValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ValueStore_GetValueByPath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetValueByPathRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ValueStoreServer).GetValueByPath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ValueStore/GetValueByPath",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ValueStoreServer).GetValueByPath(ctx, req.(*GetValueByPathRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ValueStore_GetValueById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetValueByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ValueStoreServer).GetValueById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ValueStore/GetValueById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ValueStoreServer).GetValueById(ctx, req.(*GetValueByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ValueStore_DeleteValueByPath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteValueByPathRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ValueStoreServer).DeleteValueByPath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ValueStore/DeleteValueByPath",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ValueStoreServer).DeleteValueByPath(ctx, req.(*DeleteValueByPathRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ValueStore_DeleteValueById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteValueByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ValueStoreServer).DeleteValueById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ValueStore/DeleteValueById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ValueStoreServer).DeleteValueById(ctx, req.(*DeleteValueByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ValueStore_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ValueStore",
	HandlerType: (*ValueStoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetValue",
			Handler:    _ValueStore_SetValue_Handler,
		},
		{
			MethodName: "GetValueByPath",
			Handler:    _ValueStore_GetValueByPath_Handler,
		},
		{
			MethodName: "GetValueById",
			Handler:    _ValueStore_GetValueById_Handler,
		},
		{
			MethodName: "DeleteValueByPath",
			Handler:    _ValueStore_DeleteValueByPath_Handler,
		},
		{
			MethodName: "DeleteValueById",
			Handler:    _ValueStore_DeleteValueById_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ValueStoreService.proto",
}
